apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: postgres
    password: postgres
    database: ml_monitoring
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1200
    editable: true